/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as MovieIndexRouteImport } from './routes/movie/index'
import { Route as TvIdRouteImport } from './routes/tv/$id'
import { Route as PersonIdRouteImport } from './routes/person/$id'
import { Route as MovieIdRouteImport } from './routes/movie/$id'
import { Route as GenreIdRouteImport } from './routes/genre/$id'
import { Route as DiscoverTvRouteImport } from './routes/discover/tv'
import { Route as DiscoverMovieRouteImport } from './routes/discover/movie'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIndexRoute = MovieIndexRouteImport.update({
  id: '/movie/',
  path: '/movie/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreIdRoute = GenreIdRouteImport.update({
  id: '/genre/$id',
  path: '/genre/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverTvRoute = DiscoverTvRouteImport.update({
  id: '/discover/tv',
  path: '/discover/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverMovieRoute = DiscoverMovieRouteImport.update({
  id: '/discover/movie',
  path: '/discover/movie',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover/movie': typeof DiscoverMovieRoute
  '/discover/tv': typeof DiscoverTvRoute
  '/genre/$id': typeof GenreIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/movie/': typeof MovieIndexRoute
  '/tv/': typeof TvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover/movie': typeof DiscoverMovieRoute
  '/discover/tv': typeof DiscoverTvRoute
  '/genre/$id': typeof GenreIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/movie': typeof MovieIndexRoute
  '/tv': typeof TvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover/movie': typeof DiscoverMovieRoute
  '/discover/tv': typeof DiscoverTvRoute
  '/genre/$id': typeof GenreIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/movie/': typeof MovieIndexRoute
  '/tv/': typeof TvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover/movie'
    | '/discover/tv'
    | '/genre/$id'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/movie/'
    | '/tv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover/movie'
    | '/discover/tv'
    | '/genre/$id'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/movie'
    | '/tv'
  id:
    | '__root__'
    | '/'
    | '/discover/movie'
    | '/discover/tv'
    | '/genre/$id'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/movie/'
    | '/tv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverMovieRoute: typeof DiscoverMovieRoute
  DiscoverTvRoute: typeof DiscoverTvRoute
  GenreIdRoute: typeof GenreIdRoute
  MovieIdRoute: typeof MovieIdRoute
  PersonIdRoute: typeof PersonIdRoute
  TvIdRoute: typeof TvIdRoute
  MovieIndexRoute: typeof MovieIndexRoute
  TvIndexRoute: typeof TvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/': {
      id: '/movie/'
      path: '/movie'
      fullPath: '/movie/'
      preLoaderRoute: typeof MovieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$id': {
      id: '/genre/$id'
      path: '/genre/$id'
      fullPath: '/genre/$id'
      preLoaderRoute: typeof GenreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/tv': {
      id: '/discover/tv'
      path: '/discover/tv'
      fullPath: '/discover/tv'
      preLoaderRoute: typeof DiscoverTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/movie': {
      id: '/discover/movie'
      path: '/discover/movie'
      fullPath: '/discover/movie'
      preLoaderRoute: typeof DiscoverMovieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverMovieRoute: DiscoverMovieRoute,
  DiscoverTvRoute: DiscoverTvRoute,
  GenreIdRoute: GenreIdRoute,
  MovieIdRoute: MovieIdRoute,
  PersonIdRoute: PersonIdRoute,
  TvIdRoute: TvIdRoute,
  MovieIndexRoute: MovieIndexRoute,
  TvIndexRoute: TvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
